### ISSUE TITLE
Pkg suggestion - alternate locations for certain doc files

### ISSUE THREAD

**Issue by edrozenberg** [zuno/slackpkgplus#10]
I'm trying out slackpkg+ (thanks for developing this!) and have a suggestion about location of certain files in the package.

This is regarding files in /usr/doc/slackpkg+-1.7.0/

checkrepos.sh and setupmultilib.sh
o Would for ex. /usr/share/slackpkg+/scripts/ be a good location?

slackpkg.bash_completion
o Would for ex.  /usr/share/slackpkg+/completions/ be a good location?

slackpkgplus.*.sample
o Would for ex.  /usr/share/slackpkg+/samples/ be a good location?

**Comment by zuno** [comment]
The best way for bug reports and feature requests il linuxquestions

https://www.linuxquestions.org/questions/slackware-14/slackpkg-vs-third-party-package-repository-4175427364/


There are no an high number of files in slackpkg+, so I thing that the doc directory is a good place for all that files.

in the development release (master branch) the bash_completion is in etc/bash_completion.d/

checkrepos.sh is just to make (tipically at building time) the repositories.lst in doc directory

samples files are documentations files and they are in doc directory as sample files of slackpkg official package.

**Comment by edrozenberg** [comment]
Thank you for the explanation!
