### ISSUE TITLE
Can't use special chars in mirror names?

### ISSUE THREAD

**Issue by edrozenberg** [zuno/slackpkgplus#12]
I'm using the following configuration settings, and it appears one or more of the characters `.` `-` prevent things from working properly. No error - but the priority setting does not have effect.

```
PKGS_PRIORITY=( soft1-slack64-15.0 slackware64 )
REPOPLUS=( soft1-slack64-15.0 slackpkgplus )
MIRRORPLUS['soft1-slack64-15.0']=http://soft1/software/slackware/packages/slackware64-15.0/
```

**Comment by edrozenberg** [comment]
The problem appears to be with the `.`

When I change the naming to `soft1-slack64-15` things work as expected.

**Comment by zuno** [comment]
The best way for bug reports and feature requests il linuxquestions

https://www.linuxquestions.org/questions/slackware-14/slackpkg-vs-third-party-package-repository-4175427364/

The only supported special characters supported in repository name are '-' and '_'. This is becouse the '.' char is a special character in regex and need a special treatment in code developing.
So you can call your repository soft1-slack64-15_0

**Comment by edrozenberg** [comment]
Thank you, using underscore and hyphen works fine.
