### ISSUE TITLE
No package found on arm architectures

### ISSUE THREAD

**Issue by SukkoPera** [zuno/slackpkgplus#14]
I have setup [my own remote repository for Slackware ARM](http://slackware.sukkology.net/arm/14.2/). I have generated all the repo files with alien's `gen_repos_files.sh` script but it seems slackpkg+ ignores all of my packages.

I have noticed that my packages do not appear in the `/var/lib/slackpkg/pkglist` file. I have traced this to [these lines of `/usr/libexec/slackpkg/functions.d/slackpkgplus.sh`](https://github.com/zuno/slackpkgplus/blob/master/src/slackpkgplus.sh#L834). Their purpose seem to be to filter out packages not meant for the current machine architecture, but the way the filters are setup is at least questionable, and they will **always** result in `arm` packages being filtered out, even when running on an actual ARM system.

I have worked around the issue by modifying the `FILTEREXCLUDE`, but I think a proper solution is needed.

**Comment by zuno** [comment]
slackpkg+ does not support arm.
