### ISSUE TITLE
[slackware-current] slackpkgplus broken since slackpkg-15.0.5-noarch-1

### ISSUE THREAD

**Issue by krisstoffe** [zuno/slackpkgplus#17]
slackpkg-15.0.5-noarch-1 introduced new gpg routines which seem to be incompatible with the way slackpkgplus get and import gpg keys.
As noticed in [slackware64-current changelog](http://www.slackware.com/changelog/current.php?cpu=x86_64) :
```
ap/slackpkg-15.0.5-noarch-1.txz: Upgraded.
       ...
       Harden slackpkg with respect to obtaining GPG key. (CRTS)
```

The issue has been originally reported on [Linuxquestions.org](https://www.linuxquestions.org/questions/slackware-14/cannot-update-with-slackpkg-4175696204/)

**Comment by zuno** [comment]
thanks for reporting.
pushed fix on test branch.

**Comment by zuno** [comment]
slackpkg+-1.7.6-noarch-6mt released

**Comment by krisstoffe** [comment]
It works perfectly ! Thanks !
