### ISSUE TITLE
Issued certificate has expired

### ISSUE THREAD

**Issue by kingbeowulf** [zuno/slackpkgplus#18]
Just an FYI in case you haven't noticed yet:

slackpkg update

Updating the package lists...
	Downloading...
                Signatures
	Linking /data/slackware/slackware64-current/CHECKSUMS.md5.asc
WARNING: cannot verify slakfinder.org's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
2021-10-02 20:06:50 URL:https://slakfinder.org/slackpkg+15/CHECKSUMS.md5.asc [455/455] -> "/tmp/slackpkg.E2deiS/CHECKSUMS.md5-slackpkgplus.asc" [1]
	Linking /data/slackware/multilib/current/CHECKSUMS.md5.asc

**Comment by zuno** [comment]
certaficate updated. thanks.
