### ISSUE TITLE
Missing composer/packagist

### ISSUE THREAD

**Issue by Yousha** [zuno/slackpkgplus#8]
I think it's better to convert this project to application package via Composer
And put it in Packagist (The PHP Package Repository)

**Comment by audriusk** [comment]
What does slackpkg+ (a plugin for slackpkg, a package manager for Slackware Linux, written entirely in shell script) have to do with PHP and its packaging tools?

**Comment by Yousha** [comment]
@audriusk To install and update it easily
And from anywhere

**Comment by audriusk** [comment]
I think there's been some confusion here.

According to [Wikipedia](https://en.wikipedia.org/wiki/Composer_(software)):
> Composer is an application-level package manager for the PHP programming language that provides a standard format for managing dependencies of PHP software and required libraries.

But slackpkg+ is **NOT** written in PHP and not related to it in any way whatsoever.

**Comment by Yousha** [comment]
Oh, yea sorry. Wrong project
I clicked on wrong project, instead of this https://github.com/mrossini/slakfinder
