### ISSUE TITLE
INFO: Studioware Packages have a new home

### ISSUE THREAD

**Issue by slackhead** [zuno/slackpkgplus#9]
Hi.

Not a bug. Studioware packages have move to:
http://slackware.uk/studioware/14.2/

Cheers
Dave

**Comment by zuno** [comment]
thankyou.

do you will plan to devel it for i386 and for slackware-current

**Comment by slackhead** [comment]
Not for -cuurent. We only support stable releases.
I don't know about 32bit packages anymore. We used to, but our dev team is quite small at the moment.

**Comment by zuno** [comment]
ok I will fix next days

**Comment by zuno** [comment]
updated.
